version: '3.6'

services:
  kong:
    container_name: api_gateway
    image: kong/kong-gateway:3.2.1.0
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
      - ./configs/kong/kong.yml:/kong/declarative/kong.yml
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    networks:
      - microservice
  user_service:
    container_name: user_service
    build:
      context: .
      dockerfile: ./Dockerfiles/user.Dockerfile
    image: tienpvse/user
    networks:
      - microservice
  notification_service:
    container_name: notification_service
    build:
      context: .
      dockerfile: ./Dockerfiles/notification.Dockerfile
    image: tienpvse/notification
    networks:
      - microservice

networks:
  microservice:
    name: microservice
