_format_version: '2.1'
_transform: true

services:
  - host: notification
    name: notification_service
    port: 80
    protocol: http
    routes:
      - name: notification_route
        paths:
          - /notification
        strip_path: true
  - host: user
    name: auth_service
    port: 80
    protocol: http
    path: /auth
    routes:
      - name: auth_route
        paths:
          - /auth
        strip_path: true
  - host: user
    name: user_service
    port: 80
    protocol: http
    routes:
      - name: user_route
        paths:
          - /user

        strip_path: true
upstreams:
  - name: notification
    targets:
      - target: notification_service:3000
  - name: user
    targets:
      - target: user_service:3000
plugins:
  - name: jwt
    service: notification_service
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
  - name: jwt
    service: user_service
    enabled: true
    config:
      key_claim_name: kid
      claims_to_verify:
        - exp
consumers:
  - username: login_server
    jwt_secrets:
      - algorithm: RS256
        key: this_value_to_prevent_default
        secret: this_value_to_prevent_yml_file_validation_and_wont_be_used
        rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQBnj2LAjuyxDlO4kpjoJ0Cb\nFKmuC7EHWoraSppkp+hZYiKh1Jml2j1+QMjTwqnMypKZ6RiOQVFzBh48V6OzuZcH\nM5WwtMGyLqbQfowERcS+qXO03XCVpu+d+GjNdzZ7JzLyNyYp0m56a/N6UE0c0Dha\nVe7blh4BdxwbaCuxEcq+qnqfhUCfRL+ouV0t4mTPOXNfg0/a4T2NoMX23w2Y3kWl\nclxSVJGl20yLOI5FpbHHPkD03MY/u6ZmeoyVZBSHIei84cTvj9H6QBvQxCWglLXv\nnaE14nl4fDTQeOfs4rzmTUvTIZ3NQVv6qyiPzm1XgXdk0tXaW77zC1J88FIlc0FR\nAgMBAAE=\n-----END PUBLIC KEY-----"
